CREATE TABLE `book` (
  `id` INTEGER PRIMARY KEY NOT NULL,
  `name` VARCHAR(200) DEFAULT NULL,
  `publisher` VARCHAR(40) DEFAULT NULL,
  `isbn` VARCHAR(60) DEFAULT NULL,
  `year` VARCHAR(4) DEFAULT NULL,
  `pages` INTEGER DEFAULT NULL,
  `language` VARCHAR(20) DEFAULT NULL,
  `size` VARCHAR(10) DEFAULT NULL,
  `format` VARCHAR(10) DEFAULT NULL,
  `downloadUrl` VARCHAR(200) DEFAULT NULL,
  `coverImgUrl` VARCHAR(200) DEFAULT NULL,
  `storagePath` VARCHAR(200) DEFAULT NULL,
  `authorName` VARCHAR(300) DEFAULT NULL,
  `pageUrl` VARCHAR(200) DEFAULT NULL
);
